### ISSUE TITLE
Isn't it better to use a a traditional database over a smart contract to store the hash address of the file?

### ISSUE THREAD

**Issue by arunvm123** [howardwu/IPFS-Ethereum-Storage#1]

**Comment by howardwu** [comment]
It depends on the application's use case.

If the content address points to private data for personal or trusted use, then a traditional database is perfectly fine. If the purpose of storing content and publishing its address is for other parties to inspect, modify, execute, or verify the contents in a public or generally distrusting environment, then a smart contract on a blockchain is a suitable forum to perform such logic.
